# Generated by Django 3.1.3 on 2020-11-27 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.EmailField(max_length=250)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=5)),
                ('zipcode', models.CharField(max_length=12)),
            ],
            options={
                'verbose_name_plural': 'addresses',
            },
        ),
    ]
