# Generated by Django 3.1.3 on 2020-11-27 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testadd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(max_length=250),
        ),
    ]
