# Generated by Django 3.1.3 on 2020-11-28 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testadd', '0002_auto_20201127_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='received',
            field=models.BooleanField(default=False),
        ),
    ]
